(() => {
  "use strict";
  if (window.__MEDORA_STUDY_HUB__) return;
  window.__MEDORA_STUDY_HUB__ = true;

  const cfg = window.MEDORA_CONFIG || {};
  if (!window.supabase?.createClient || !cfg.SUPABASE_URL || !cfg.SUPABASE_PUBLISHABLE_KEY) return;
  const db = window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true }
  });

  const S = { user:null, rooms:[], members:[], tasks:[], completions:[], schedules:[], quizzes:[], questions:[], answers:[], profiles:[], connections:[], tab:"rooms", selectedRoom:null, timer:null };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const pad=n=>String(n).padStart(2,"0");
  const dmy=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"—":`${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`};
  const hm=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"":`${pad(d.getHours())}:${pad(d.getMinutes())}`};
  const profileName=id=>{if(id===S.user?.id)return "You";const p=S.profiles.find(x=>x.user_id===id);return p?.display_name||p?.username||"Study partner"};
  const isOwner=r=>r?.owner_id===S.user?.id;
  const roomMembers=id=>[{room_id:id,user_id:S.rooms.find(r=>r.id===id)?.owner_id,role:"owner"},...S.members.filter(m=>m.room_id===id)].filter((m,i,a)=>m.user_id&&a.findIndex(x=>x.user_id===m.user_id)===i);
  const roomTasks=id=>S.tasks.filter(t=>t.room_id===id).sort((a,b)=>(a.position||0)-(b.position||0));
  const roomSchedules=id=>S.schedules.filter(x=>x.room_id===id).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
  const roomQuizzes=id=>S.quizzes.filter(x=>x.room_id===id).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
  const studyActive=()=>!!document.querySelector('[data-study-link].active');

  function addStyles(){
    if($("#studyHubStyle")) return;
    const s=document.createElement("style"); s.id="studyHubStyle"; s.textContent=`
      .sh-root{display:grid;gap:16px}.sh-hero{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(260px,.65fr);gap:18px;padding:28px;border-radius:27px;color:#fff;background:radial-gradient(circle at 92% 7%,rgba(132,88,229,.43),transparent 30%),radial-gradient(circle at 0 100%,rgba(24,183,168,.27),transparent 34%),linear-gradient(135deg,#0c1832,#1c2d60 68%,#2b245f)}.sh-ey{font-size:10px;font-weight:850;letter-spacing:.12em;color:#ffffff9c}.sh-hero h1{margin:7px 0 9px;font-size:clamp(34px,4vw,50px);line-height:1.03;letter-spacing:-.05em}.sh-hero p{margin:0;max-width:780px;color:#ffffffaa;line-height:1.58}.sh-hero-side{display:grid;align-content:center;gap:8px;padding:19px;border:1px solid #ffffff20;border-radius:19px;background:#ffffff0c}.sh-hero-side strong{font-size:20px}.sh-hero-side small{color:#ffffff9d;line-height:1.45}.sh-btn{min-height:40px;padding:0 13px;border:0;border-radius:11px;background:#fff;color:#17213a;font-weight:850;cursor:pointer}.sh-btn.alt{color:#fff;background:#ffffff12;border:1px solid #ffffff22}.sh-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:18px}
      .sh-tabs{display:flex;gap:5px;width:max-content;padding:5px;border-radius:14px;background:#e9eff7}.sh-tabs button{min-height:40px;padding:0 15px;border:0;border-radius:10px;background:transparent;color:#68748a;font-weight:800;cursor:pointer}.sh-tabs button.active{background:#fff;color:#253047;box-shadow:0 5px 15px #1d284612}.sh-card{padding:18px;border:1px solid #e0e6ef;border-radius:19px;background:#fff}.sh-head{display:flex;align-items:end;justify-content:space-between;gap:12px}.sh-head h2{margin:0;font-size:23px}.sh-head p{margin:4px 0 0;color:#7d8799;font-size:12px}.sh-soft{min-height:36px;padding:0 11px;border:0;border-radius:10px;background:#eef1ff;color:#5368d6;font-size:10px;font-weight:850;cursor:pointer}
      .sh-room-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:13px}.sh-room{display:grid;gap:11px;padding:16px;border:1px solid #e1e6ef;border-radius:17px;background:#fff;cursor:pointer;transition:.15s}.sh-room:hover{transform:translateY(-1px);box-shadow:0 12px 26px #29345010}.sh-room.active{border-color:#9fb1f4;box-shadow:0 0 0 3px #617bf010}.sh-room-top{display:flex;gap:10px}.sh-room-art{width:48px;height:48px;display:grid;place-items:center;border-radius:15px;background:linear-gradient(135deg,#eaf9f5,#f1edff);font-size:25px}.sh-room h3{margin:2px 0 4px}.sh-room small{color:#7d8798}.sh-tags{display:flex;gap:6px;flex-wrap:wrap}.sh-tag{padding:5px 8px;border-radius:999px;background:#f1f4f8;color:#637087;font-size:9px;font-weight:800}.sh-tag.together{background:#edf8f2;color:#187458}
      .sh-room-board{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:11px}.sh-cartoon{position:relative;overflow:hidden;padding:20px;border-radius:20px;background:linear-gradient(145deg,#fbfdff,#f3f7ff);border:1px solid #e3e8f1}.sh-cartoon:after{content:'📚  ✏️  ⭐';position:absolute;right:18px;top:15px;font-size:24px;opacity:.75}.sh-cartoon h3{margin:0 0 4px}.sh-cartoon p{margin:0;color:#7c8699;font-size:11px}.sh-tasks{display:grid;gap:7px;margin-top:14px}.sh-task{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:9px;padding:10px;border-radius:13px;background:#fff;border:1px solid #edf0f5}.sh-check{width:31px;height:31px;border:1px solid #d8e0ea;border-radius:9px;background:#fff;color:#8690a2;cursor:pointer;font-weight:900}.sh-check.done{background:#e9f8f1;border-color:#79cba9;color:#167653}.sh-task strong,.sh-task small{display:block}.sh-task small{margin-top:3px;color:#8991a1;font-size:9px}.sh-task-score{font-size:10px;font-weight:850;color:#5f6b82}.sh-race{padding:17px;border-radius:18px;background:linear-gradient(135deg,#fffaf1,#fff5f5);border:1px solid #f0e5d3}.sh-race h3{margin:0}.sh-race p{color:#8b7c72;font-size:10px;line-height:1.45}.sh-leader{display:grid;gap:7px;margin-top:12px}.sh-leader-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:8px;align-items:center;padding:9px;border-radius:11px;background:#fff}.sh-place{width:28px;height:28px;display:grid;place-items:center;border-radius:50%;background:#f1f4f8;font-size:11px;font-weight:900}.sh-place.first{background:#fff0b8}.sh-leader-row strong,.sh-leader-row small{display:block}.sh-leader-row small{color:#8a92a1;font-size:9px}.sh-leader-row b{font-size:10px}
      .sh-schedule-list,.sh-quiz-list{display:grid;gap:8px;margin-top:12px}.sh-schedule{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px;border-radius:13px;background:#f7f9fc}.sh-datebox{width:50px;text-align:center;padding:8px;border-radius:11px;background:#fff;color:#4d5870;font-size:10px;font-weight:850}.sh-schedule strong,.sh-schedule small{display:block}.sh-schedule small{margin-top:3px;color:#858ea0;font-size:9px}
      .sh-quiz{padding:15px;border:1px solid #e2e7ef;border-radius:16px;background:#fff}.sh-quiz-top{display:flex;justify-content:space-between;gap:12px}.sh-quiz h3{margin:0}.sh-quiz small{color:#818a9b}.sh-race-question{margin-top:13px;padding:17px;border-radius:17px;background:linear-gradient(135deg,#f8fbff,#f6f3ff);border:1px solid #e3e6f0}.sh-race-question h3{margin:0 0 13px}.sh-options{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sh-option{min-height:48px;padding:10px;border:1px solid #dde4ee;border-radius:12px;background:#fff;text-align:left;cursor:pointer;font-weight:750}.sh-option:hover{border-color:#9eacee}.sh-option.answered{opacity:.55}.sh-winner{margin-top:11px;padding:11px;border-radius:12px;background:#fff6cf;color:#745d08;font-size:11px;font-weight:800}
      .sh-modal-bg{position:fixed;z-index:560;inset:0;display:grid;place-items:center;padding:18px;background:#0c15287c;backdrop-filter:blur(5px)}.sh-modal{width:min(690px,100%);max-height:88vh;overflow:auto;padding:23px;border-radius:22px;background:#fff}.sh-modal-h{display:flex;justify-content:space-between;gap:12px}.sh-modal-h h2{margin:4px 0 0}.sh-x{width:37px;height:37px;border:0;border-radius:50%;background:#f0f3f7;font-size:20px;cursor:pointer}.sh-form{display:grid;gap:12px;margin-top:18px}.sh-form label{display:grid;gap:6px;color:#4e596d;font-size:11px;font-weight:800}.sh-form input,.sh-form textarea,.sh-form select{min-height:43px;padding:9px 11px;border:1px solid #dfe4ed;border-radius:11px;background:#fff}.sh-two{display:grid;grid-template-columns:1fr 1fr;gap:9px}.sh-people{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.sh-person{display:flex;align-items:center;gap:8px;padding:9px;border:1px solid #e1e6ef;border-radius:11px;cursor:pointer}.sh-person input{min-height:auto;width:auto}.sh-modal-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:5px}.sh-save{min-height:41px;padding:0 13px;border:0;border-radius:11px;color:#fff;font-weight:850;background:linear-gradient(115deg,#19b8aa,#667ff2 52%,#8558ea);cursor:pointer}.sh-empty{padding:30px;border:1px dashed #dce3ec;border-radius:16px;text-align:center;color:#7f899b}
      @media(max-width:1050px){.sh-room-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.sh-room-board,.sh-hero{grid-template-columns:1fr}}@media(max-width:700px){.sh-room-grid{grid-template-columns:1fr}.sh-options,.sh-two,.sh-people{grid-template-columns:1fr}.sh-tabs{width:100%;display:grid;grid-template-columns:repeat(4,1fr)}.sh-tabs button{padding:0 5px;font-size:10px}}
    `; document.head.appendChild(s);
  }

  function ensureNav(){
    const main=$(".main-nav"); if(main&&!main.querySelector("[data-study-link]")){const b=document.createElement("button");b.type="button";b.className="nav-item";b.dataset.studyLink="true";b.innerHTML='<span class="nav-icon">✎</span><span>Study</span>';const activity=main.querySelector('[data-activity-link]');if(activity?.nextSibling)main.insertBefore(b,activity.nextSibling);else main.appendChild(b)}
    const mobile=$(".mobile-nav"); if(mobile&&!mobile.querySelector("[data-study-link]")){const b=document.createElement("button");b.type="button";b.className="mobile-nav-item";b.dataset.studyLink="true";b.innerHTML='<span>✎</span><small>Study</small>';const activity=mobile.querySelector('[data-activity-link]');if(activity?.nextSibling)mobile.insertBefore(b,activity.nextSibling);else mobile.appendChild(b)}
  }
  function setActive(){ $$(".nav-item.active,.mobile-nav-item.active,[data-wall-link].active,[data-activity-link].active").forEach(x=>x.classList.remove("active")); $$('[data-study-link]').forEach(x=>x.classList.add("active")); }
  function clearActive(){ $$('[data-study-link]').forEach(x=>x.classList.remove("active")); }

  async function load(){
    const {data:{user}}=await db.auth.getUser(); if(!user)return false; S.user=user;
    const q=await Promise.all([
      db.from("study_rooms").select("*").order("created_at",{ascending:false}),
      db.from("study_room_members").select("*"), db.from("study_tasks").select("*"), db.from("study_task_completions").select("*"),
      db.from("study_schedules").select("*"), db.from("study_quizzes").select("*"), db.from("study_quiz_questions").select("*"), db.from("study_quiz_answers").select("*"),
      db.from("public_profiles").select("user_id,display_name,username,is_visible"), db.from("connections").select("requester_id,addressee_id,status").eq("status","accepted")
    ]); if(q.some(x=>x.error)){console.warn("Study load failed",q.find(x=>x.error)?.error);return false}
    [S.rooms,S.members,S.tasks,S.completions,S.schedules,S.quizzes,S.questions,S.answers,S.profiles,S.connections]=q.map(x=>x.data||[]);
    if(!S.selectedRoom||!S.rooms.some(r=>r.id===S.selectedRoom))S.selectedRoom=S.rooms[0]?.id||null; return true;
  }

  function connectedPeople(){const u=S.user.id;return S.connections.map(c=>c.requester_id===u?c.addressee_id:c.requester_id).filter(Boolean).map(id=>({id,name:profileName(id)}))}
  function completionCount(roomId,userId){const ids=new Set(roomTasks(roomId).map(t=>t.id));return S.completions.filter(c=>c.user_id===userId&&ids.has(c.task_id)).length}
  function firstFinished(roomId,userId){const ts=roomTasks(roomId);if(!ts.length)return null;const cs=ts.map(t=>S.completions.find(c=>c.task_id===t.id&&c.user_id===userId)).filter(Boolean);if(cs.length!==ts.length)return null;return new Date(Math.max(...cs.map(c=>new Date(c.completed_at).getTime())))}
  function leaderboard(room){return roomMembers(room.id).map(m=>({id:m.user_id,name:profileName(m.user_id),count:completionCount(room.id,m.user_id),finish:firstFinished(room.id,m.user_id)})).sort((a,b)=>{if(a.finish&&b.finish)return a.finish-b.finish;if(a.finish)return-1;if(b.finish)return 1;return b.count-a.count})}

  function roomCard(r){const tasks=roomTasks(r.id),mine=completionCount(r.id,S.user.id);return `<article class="sh-room ${S.selectedRoom===r.id?'active':''}" data-room="${r.id}"><div class="sh-room-top"><div class="sh-room-art">${r.mode==='together'?'🤝':'📝'}</div><div><h3>${esc(r.title)}</h3><small>${esc(r.subject||'Study room')}</small></div></div><div class="sh-tags"><span class="sh-tag ${r.mode==='together'?'together':''}">${r.mode==='together'?'Do it together':'Share progress'}</span><span class="sh-tag">${roomMembers(r.id).length} people</span><span class="sh-tag">${mine}/${tasks.length} done</span></div></article>`}
  function roomsView(){return `<section class="sh-card"><div class="sh-head"><div><h2>Study rooms</h2><p>Create a private accountability room or a shared race.</p></div><button class="sh-soft" data-new-room>+ New room</button></div><div class="sh-room-grid">${S.rooms.length?S.rooms.map(roomCard).join(''):'<div class="sh-empty">No study rooms yet.</div>'}</div></section>${S.selectedRoom?roomBoard(S.rooms.find(r=>r.id===S.selectedRoom)):''}`}

  function roomBoard(room){if(!room)return'';const tasks=roomTasks(room.id), leaders=leaderboard(room);return `<section class="sh-room-board"><article class="sh-cartoon"><div class="sh-head"><div><h3>📝 ${esc(room.title)} checklist</h3><p>Tick tasks as you finish. The first person to complete the whole list gets the flag.</p></div><button class="sh-soft" data-add-task="${room.id}">+ Task</button></div><div class="sh-tasks">${tasks.length?tasks.map(t=>{const c=S.completions.find(x=>x.task_id===t.id&&x.user_id===S.user.id);return `<div class="sh-task"><button class="sh-check ${c?'done':''}" data-toggle-task="${t.id}">${c?'✓':'○'}</button><div><strong>${esc(t.title)}</strong><small>${t.due_at?`Due ${dmy(t.due_at)} ${hm(t.due_at)}`:'No deadline'}</small></div><span class="sh-task-score">${t.points||1} pt</span></div>`}).join(''):'<div class="sh-empty">Add your cartoon checklist tasks here.</div>'}</div></article><aside class="sh-race"><h3>🏁 Checklist race</h3><p>Progress is shared live. Finishing all tasks first wins this room’s checklist race.</p><div class="sh-leader">${leaders.map((x,i)=>`<div class="sh-leader-row"><span class="sh-place ${i===0&&x.finish?'first':''}">${i===0&&x.finish?'🏆':i+1}</span><div><strong>${esc(x.name)}</strong><small>${x.finish?`Finished ${hm(x.finish)}`:`${x.count}/${tasks.length} tasks`}</small></div><b>${tasks.length?Math.round(x.count/tasks.length*100):0}%</b></div>`).join('')}</div></aside></section>`}

  function scheduleView(){const room=S.rooms.find(r=>r.id===S.selectedRoom);if(!room)return'<div class="sh-empty">Choose or create a room first.</div>';const items=roomSchedules(room.id);return `<section class="sh-card"><div class="sh-head"><div><h2>${esc(room.title)} schedule</h2><p>Shared study sessions everyone in the room can see.</p></div><button class="sh-soft" data-add-schedule="${room.id}">+ Session</button></div><div class="sh-schedule-list">${items.length?items.map(x=>`<div class="sh-schedule"><div class="sh-datebox">${dmy(x.starts_at).slice(0,5)}</div><div><strong>${esc(x.title)}</strong><small>${dmy(x.starts_at)} · ${hm(x.starts_at)}${x.ends_at?` → ${hm(x.ends_at)}`:''}${x.notes?` · ${esc(x.notes)}`:''}</small></div><span class="sh-tag">shared</span></div>`).join(''):'<div class="sh-empty">No scheduled study sessions yet.</div>'}</div></section>`}

  function challengeView(){const room=S.rooms.find(r=>r.id===S.selectedRoom);if(!room)return'<div class="sh-empty">Choose or create a room first.</div>';return `<section class="sh-card"><div class="sh-head"><div><h2>Checklist challenge</h2><p>A friendly race based on the same shared to-do list.</p></div></div>${roomBoard(room)}</section>`}

  function quizView(){const room=S.rooms.find(r=>r.id===S.selectedRoom);if(!room)return'<div class="sh-empty">Choose or create a room first.</div>';const qs=roomQuizzes(room.id);return `<section class="sh-card"><div class="sh-head"><div><h2>⚡ Quiz race</h2><p>Ask colleagues a four-choice question. First correct answer wins.</p></div><button class="sh-soft" data-new-quiz="${room.id}">+ New race</button></div><div class="sh-quiz-list">${qs.length?qs.map(quizCard).join(''):'<div class="sh-empty">No quiz races yet.</div>'}</div></section>`}
  function quizCard(q){const question=S.questions.filter(x=>x.quiz_id===q.id).sort((a,b)=>a.position-b.position)[0];const ans=question?S.answers.filter(a=>a.question_id===question.id).sort((a,b)=>new Date(a.answered_at)-new Date(b.answered_at)):[];const winner=ans.find(a=>a.is_correct);const mine=ans.find(a=>a.user_id===S.user.id);return `<article class="sh-quiz"><div class="sh-quiz-top"><div><h3>${esc(q.title)}</h3><small>${q.status} · ${q.question_seconds}s</small></div>${isOwner(S.rooms.find(r=>r.id===q.room_id))?`<button class="sh-soft" data-start-quiz="${q.id}">${q.status==='live'?'Live':'Start race'}</button>`:''}</div>${question&&q.status==='live'?`<div class="sh-race-question"><h3>${esc(question.prompt)}</h3><div class="sh-options">${['A','B','C','D'].map(k=>`<button class="sh-option ${mine?'answered':''}" data-answer="${question.id}" data-option="${k}" ${mine?'disabled':''}><b>${k}</b> ${esc(question['option_'+k.toLowerCase()])}</button>`).join('')}</div>${winner?`<div class="sh-winner">🏆 ${esc(profileName(winner.user_id))} answered correctly first${winner.response_ms!=null?` in ${(winner.response_ms/1000).toFixed(1)}s`:''}.</div>`:''}</div>`:question?`<div class="sh-race-question"><small>Question ready. Start the race when everyone is in the room.</small></div>`:''}</article>`}

  function render(){if(!studyActive())return;const root=$("#screenContainer");if(!root)return;const k=$("#topbarKicker"),t=$("#topbarTitle");if(k)k.textContent="STUDY";if(t)t.textContent="Learn together. Finish stronger.";root.innerHTML=`<section class="screen sh-root"><section class="sh-hero"><div><span class="sh-ey">MEDORA STUDY</span><h1>Turn studying into something social.</h1><p>Create rooms, build shared schedules, race through a cartoon checklist, or challenge colleagues to fast quiz battles.</p><div class="sh-actions"><button class="sh-btn" data-new-room>+ Create study room</button><button class="sh-btn alt" data-tab="quiz">Start a quiz race</button></div></div><aside class="sh-hero-side"><strong>Study together without losing focus.</strong><small>Choose whether friends only see progress or actually complete the same schedule and checklist with you.</small></aside></section><nav class="sh-tabs">${[['rooms','Rooms'],['schedule','Schedule'],['challenge','Checklist race'],['quiz','Quiz race']].map(([x,l])=>`<button data-tab="${x}" class="${S.tab===x?'active':''}">${l}</button>`).join('')}</nav>${S.tab==='rooms'?roomsView():S.tab==='schedule'?scheduleView():S.tab==='challenge'?challengeView():quizView()}<div id="shModal"></div></section>`;bind()}

  function bind(){ $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{S.tab=b.dataset.tab;render()})); $$('[data-room]').forEach(b=>b.addEventListener('click',()=>{S.selectedRoom=b.dataset.room;render()})); $$('[data-new-room]').forEach(b=>b.addEventListener('click',roomModal)); $$('[data-add-task]').forEach(b=>b.addEventListener('click',()=>taskModal(b.dataset.addTask))); $$('[data-toggle-task]').forEach(b=>b.addEventListener('click',()=>toggleTask(b.dataset.toggleTask))); $$('[data-add-schedule]').forEach(b=>b.addEventListener('click',()=>scheduleModal(b.dataset.addSchedule))); $$('[data-new-quiz]').forEach(b=>b.addEventListener('click',()=>quizModal(b.dataset.newQuiz))); $$('[data-start-quiz]').forEach(b=>b.addEventListener('click',()=>startQuiz(b.dataset.startQuiz))); $$('[data-answer]').forEach(b=>b.addEventListener('click',()=>answerQuiz(b.dataset.answer,b.dataset.option))) }
  const modal=html=>{const h=$("#shModal");if(h)h.innerHTML=`<div class="sh-modal-bg"><section class="sh-modal">${html}</section></div>`}; const close=()=>{const h=$("#shModal");if(h)h.innerHTML=""};

  function roomModal(){const people=connectedPeople();modal(`<div class="sh-modal-h"><div><span class="sh-ey" style="color:#71809b">NEW STUDY ROOM</span><h2>Create a room</h2></div><button class="sh-x" data-close>×</button></div><form class="sh-form" id="shRoomForm"><label>Room name<input id="shRoomTitle" required placeholder="Cardiology finals"></label><div class="sh-two"><label>Subject<input id="shRoomSubject" placeholder="Cardiology"></label><label>Mode<select id="shRoomMode"><option value="progress">Share progress</option><option value="together">Do it together</option></select></label></div><label>Description<textarea id="shRoomDesc" rows="2" placeholder="What are you studying together?"></textarea></label><label>Invite colleagues<div class="sh-people">${people.length?people.map(p=>`<label class="sh-person"><input type="checkbox" value="${p.id}" data-person><span>${esc(p.name)}</span></label>`).join(''):'<small>No accepted Medora connections yet.</small>'}</div></label><div class="sh-modal-actions"><button type="button" class="sh-soft" data-close>Cancel</button><button class="sh-save">Create room →</button></div></form>`); $$('[data-close]').forEach(b=>b.onclick=close); $('#shRoomForm').onsubmit=createRoom}
  async function createRoom(e){e.preventDefault();const {data:r,error}=await db.from('study_rooms').insert({owner_id:S.user.id,title:$('#shRoomTitle').value.trim(),subject:$('#shRoomSubject').value.trim()||null,description:$('#shRoomDesc').value.trim()||null,mode:$('#shRoomMode').value}).select().single();if(error)return alert(error.message);const ids=$$('[data-person]:checked').map(x=>x.value);if(ids.length)await db.from('study_room_members').insert(ids.map(id=>({room_id:r.id,user_id:id,role:'member'})));close();await refresh(r.id)}
  function taskModal(roomId){modal(`<div class="sh-modal-h"><div><span class="sh-ey" style="color:#71809b">CHECKLIST</span><h2>Add study task</h2></div><button class="sh-x" data-close>×</button></div><form class="sh-form" id="shTaskForm"><label>Task<input id="shTaskTitle" required placeholder="Finish chapter 3"></label><div class="sh-two"><label>Due<input id="shTaskDue" type="datetime-local"></label><label>Points<input id="shTaskPoints" type="number" min="1" value="1"></label></div><div class="sh-modal-actions"><button type="button" class="sh-soft" data-close>Cancel</button><button class="sh-save">Add task →</button></div></form>`);$$('[data-close]').forEach(b=>b.onclick=close);$('#shTaskForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('study_tasks').insert({room_id:roomId,created_by:S.user.id,title:$('#shTaskTitle').value.trim(),due_at:$('#shTaskDue').value?new Date($('#shTaskDue').value).toISOString():null,points:Number($('#shTaskPoints').value)||1,position:roomTasks(roomId).length});if(error)return alert(error.message);close();await refresh(roomId)}}
  async function toggleTask(taskId){const c=S.completions.find(x=>x.task_id===taskId&&x.user_id===S.user.id);const q=c?await db.from('study_task_completions').delete().eq('task_id',taskId).eq('user_id',S.user.id):await db.from('study_task_completions').insert({task_id:taskId,user_id:S.user.id});if(q.error)return alert(q.error.message);await refresh(S.selectedRoom)}
  function scheduleModal(roomId){modal(`<div class="sh-modal-h"><div><span class="sh-ey" style="color:#71809b">SCHEDULE</span><h2>Add study session</h2></div><button class="sh-x" data-close>×</button></div><form class="sh-form" id="shScheduleForm"><label>Session title<input id="shScheduleTitle" required placeholder="ECG review"></label><div class="sh-two"><label>Starts<input id="shScheduleStart" type="datetime-local" required></label><label>Ends<input id="shScheduleEnd" type="datetime-local"></label></div><label>Notes<input id="shScheduleNotes" placeholder="Zoom / library / topic"></label><div class="sh-modal-actions"><button type="button" class="sh-soft" data-close>Cancel</button><button class="sh-save">Share session →</button></div></form>`);$$('[data-close]').forEach(b=>b.onclick=close);$('#shScheduleForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('study_schedules').insert({room_id:roomId,created_by:S.user.id,title:$('#shScheduleTitle').value.trim(),starts_at:new Date($('#shScheduleStart').value).toISOString(),ends_at:$('#shScheduleEnd').value?new Date($('#shScheduleEnd').value).toISOString():null,notes:$('#shScheduleNotes').value.trim()||null});if(error)return alert(error.message);close();await refresh(roomId)}}
  function quizModal(roomId){modal(`<div class="sh-modal-h"><div><span class="sh-ey" style="color:#71809b">QUIZ RACE</span><h2>Create a one-question race</h2></div><button class="sh-x" data-close>×</button></div><form class="sh-form" id="shQuizForm"><label>Race title<input id="shQuizTitle" required placeholder="ECG lightning round"></label><label>Question<textarea id="shPrompt" required rows="2"></textarea></label><div class="sh-two"><label>A<input id="shA" required></label><label>B<input id="shB" required></label><label>C<input id="shC" required></label><label>D<input id="shD" required></label></div><div class="sh-two"><label>Correct answer<select id="shCorrect"><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label>Timer (seconds)<input id="shSeconds" type="number" min="5" max="300" value="30"></label></div><label>Explanation<input id="shExplain" placeholder="Shown after the race"></label><div class="sh-modal-actions"><button type="button" class="sh-soft" data-close>Cancel</button><button class="sh-save">Create race →</button></div></form>`);$$('[data-close]').forEach(b=>b.onclick=close);$('#shQuizForm').onsubmit=async e=>{e.preventDefault();const {data:q,error}=await db.from('study_quizzes').insert({room_id:roomId,created_by:S.user.id,title:$('#shQuizTitle').value.trim(),question_seconds:Number($('#shSeconds').value)||30}).select().single();if(error)return alert(error.message);const {error:qErr}=await db.from('study_quiz_questions').insert({quiz_id:q.id,position:0,prompt:$('#shPrompt').value.trim(),option_a:$('#shA').value.trim(),option_b:$('#shB').value.trim(),option_c:$('#shC').value.trim(),option_d:$('#shD').value.trim(),correct_option:$('#shCorrect').value,explanation:$('#shExplain').value.trim()||null});if(qErr)return alert(qErr.message);close();await refresh(roomId)}}
  async function startQuiz(id){const {error}=await db.from('study_quizzes').update({status:'live',started_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await refresh(S.selectedRoom);poll()}
  async function answerQuiz(questionId,option){const q=S.questions.find(x=>x.id===questionId), quiz=S.quizzes.find(x=>x.id===q?.quiz_id);if(!q||!quiz)return;const response=Math.max(0,new Date()-new Date(quiz.started_at));const {error}=await db.from('study_quiz_answers').insert({question_id:questionId,user_id:S.user.id,answer:option,is_correct:option===q.correct_option,response_ms:Math.round(response)});if(error)return alert(error.message);await refresh(S.selectedRoom)}

  async function refresh(roomId){await load();if(roomId)S.selectedRoom=roomId;render()}
  function poll(){clearInterval(S.timer);S.timer=setInterval(async()=>{if(!studyActive())return;const live=S.quizzes.some(q=>q.status==='live');if(live)await refresh(S.selectedRoom)},2000)}
  async function openStudy(){setActive();try{localStorage.setItem('medora.lastScreen','study')}catch{};const root=$("#screenContainer");if(root)root.innerHTML='<section class="screen sh-root"><div class="sh-empty">Loading Study…</div></section>';if(await load())render()}
  function init(){addStyles();ensureNav();document.addEventListener('click',e=>{if(e.target.closest('[data-study-link]')){e.preventDefault();openStudy();return}if(e.target.closest('[data-screen],[data-wall-link],[data-activity-link]'))clearActive()},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.sh-modal-bg')){close();e.preventDefault()}},true);poll()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();