(() => {
  "use strict";
  if (window.__MEDORA_STUDY_HUB_PRO__) return;
  window.__MEDORA_STUDY_HUB_PRO__ = true;

  const cfg = window.MEDORA_CONFIG || {};
  if (!window.supabase?.createClient || !cfg.SUPABASE_URL || !cfg.SUPABASE_PUBLISHABLE_KEY) return;
  const db = window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true }
  });

  const P = {
    user:null, presence:[], rounds:[], focusMembers:[], flashcards:[], reviews:[], notes:[], resources:[], targets:[],
    teach:[], teachFeedback:[], rooms:[], members:[], tasks:[], completions:[], schedules:[], quizzes:[], questions:[], answers:[],
    profiles:[], activityTypes:[], activitySessions:[], loaded:false, heartbeat:null, clock:null
  };

  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const pad=n=>String(n).padStart(2,"0");
  const mins=(a,b)=>Math.max(0,(b-a)/60000);
  const dur=m=>{m=Math.round(m||0);const h=Math.floor(m/60),x=m%60;return h?`${h}h${x?` ${x}m`:""}`:`${x}m`};
  const sameDay=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
  const roomName=id=>P.rooms.find(r=>r.id===id)?.title||"Personal study";
  const personName=id=>id===P.user?.id?"You":(P.profiles.find(p=>p.user_id===id)?.display_name||P.profiles.find(p=>p.user_id===id)?.username||"Study partner");
  const norm=s=>String(s||"").trim().toLowerCase().replace(/\s+/g," ");
  const studyOpen=()=>!!document.querySelector('[data-study-link].active');

  function style(){
    if($("#studyHubProStyle")) return;
    const s=document.createElement("style"); s.id="studyHubProStyle"; s.textContent=`
      #shpPanel{display:grid;gap:12px}.shp-live{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(300px,.95fr);gap:11px}.shp-box{padding:17px;border:1px solid #e0e6ef;border-radius:18px;background:#fff}.shp-box h3{margin:0;font-size:17px}.shp-box p{margin:5px 0 0;color:#7d8799;font-size:10px;line-height:1.45}.shp-row{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:12px}.shp-input,.shp-select{min-height:40px;padding:0 11px;border:1px solid #dfe5ee;border-radius:11px;background:#fff;color:#344057}.shp-input{flex:1;min-width:180px}.shp-btn{min-height:40px;padding:0 12px;border:0;border-radius:11px;background:#eef1ff;color:#5268d5;font-size:10px;font-weight:850;cursor:pointer}.shp-btn.primary{color:#fff;background:linear-gradient(115deg,#18b6a8,#657ff1 55%,#8559e9)}.shp-btn.stop{background:#fff0f3;color:#a54255}.shp-btn.green{background:#e9f8f1;color:#167653}.shp-presence-list{display:grid;gap:6px;margin-top:11px}.shp-person{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:8px;align-items:center;padding:9px;border-radius:12px;background:#f7f9fc}.shp-avatar{width:34px;height:34px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(135deg,#eaf9f5,#f1edff);font-weight:900;color:#59677c}.shp-person strong,.shp-person small{display:block}.shp-person small{margin-top:2px;color:#8991a1;font-size:9px}.shp-state{padding:4px 7px;border-radius:999px;background:#e9f8f1;color:#147458;font-size:8px;font-weight:850}.shp-state.period{background:#eef1ff;color:#5268d5}
      .shp-tools{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.shp-tool{display:grid;gap:7px;min-height:116px;padding:14px;border:1px solid #e1e6ef;border-radius:16px;background:#fff;text-align:left;cursor:pointer;transition:.14s}.shp-tool:hover{transform:translateY(-1px);box-shadow:0 10px 24px #26314f10}.shp-tool span{font-size:22px}.shp-tool strong{font-size:12px}.shp-tool small{color:#818a9b;font-size:9px;line-height:1.4}.shp-strip{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:10px}.shp-mission{padding:17px;border-radius:18px;background:linear-gradient(145deg,#fbfdff,#f3f7ff);border:1px solid #e3e8f1}.shp-mission h3,.shp-coach h3{margin:0}.shp-mission-list{display:grid;gap:6px;margin-top:10px}.shp-mission-item{display:flex;justify-content:space-between;gap:8px;padding:9px;border-radius:11px;background:#fff;font-size:10px}.shp-coach{padding:17px;border-radius:18px;background:linear-gradient(135deg,#fffaf1,#fff6f8);border:1px solid #f0e5d9}.shp-coach p{color:#746f75}.shp-chiprow{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.shp-chip{padding:5px 8px;border-radius:999px;background:#f1f4f8;color:#647086;font-size:8px;font-weight:850}.shp-focus-live{margin-top:11px;padding:12px;border-radius:14px;background:#edf9f4;border:1px solid #caeadc}.shp-focus-live strong,.shp-focus-live small{display:block}.shp-focus-live small{margin-top:4px;color:#60766d}.shp-focus-time{font-size:24px!important;color:#167653}
      .shp-modal-bg{position:fixed;z-index:620;inset:0;display:grid;place-items:center;padding:18px;background:#0c152884;backdrop-filter:blur(5px)}.shp-modal{width:min(780px,100%);max-height:90vh;overflow:auto;padding:23px;border-radius:22px;background:#fff}.shp-modal-h{display:flex;justify-content:space-between;gap:12px}.shp-modal-h h2{margin:4px 0 0}.shp-x{width:37px;height:37px;border:0;border-radius:50%;background:#f0f3f7;font-size:20px;cursor:pointer}.shp-form{display:grid;gap:11px;margin-top:17px}.shp-form label{display:grid;gap:6px;color:#4e596d;font-size:10px;font-weight:800}.shp-form input,.shp-form select,.shp-form textarea{min-height:42px;padding:9px 11px;border:1px solid #dfe4ed;border-radius:11px;background:#fff}.shp-two{display:grid;grid-template-columns:1fr 1fr;gap:9px}.shp-modal-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:5px}.shp-save{min-height:42px;padding:0 14px;border:0;border-radius:11px;color:#fff;background:linear-gradient(115deg,#19b8aa,#667ff2 52%,#8558ea);font-weight:850;cursor:pointer}.shp-list{display:grid;gap:8px;margin-top:13px}.shp-card{padding:13px;border:1px solid #e2e7ef;border-radius:14px;background:#fff}.shp-card h4{margin:0}.shp-card small{color:#858ea0}.shp-card-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.shp-card-actions button{min-height:33px;padding:0 10px;border:0;border-radius:9px;background:#f0f3f8;color:#5d687e;font-size:9px;font-weight:800;cursor:pointer}.shp-card-actions button.good{background:#e9f8f1;color:#167653}.shp-card-actions button.bad{background:#fff0f3;color:#a54255}.shp-face{padding:15px;border-radius:14px;background:#f7f9fc;font-size:14px;font-weight:800}.shp-answer{margin-top:8px;padding:13px;border-radius:13px;background:#eef8f4;color:#395f52}.shp-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.shp-metric{padding:12px;border-radius:13px;background:#f7f9fc}.shp-metric small,.shp-metric strong{display:block}.shp-metric small{color:#858ea0;font-size:8px}.shp-metric strong{margin-top:4px;font-size:19px}.shp-topic-list{display:grid;gap:7px;margin-top:11px}.shp-topic{display:grid;grid-template-columns:minmax(120px,.45fr) minmax(0,1fr) auto;gap:8px;align-items:center;font-size:10px}.shp-track{height:7px;border-radius:999px;background:#edf1f6;overflow:hidden}.shp-track span{display:block;height:100%;background:linear-gradient(90deg,#e86a78,#f0b34a,#31b77b)}.shp-rec{padding:12px;border-radius:13px;background:#f7f9fc}.shp-rec+ .shp-rec{margin-top:7px}.shp-rec b,.shp-rec span{display:block}.shp-rec span{margin-top:4px;color:#7d8798;font-size:9px;line-height:1.45}.shp-empty{padding:24px;border:1px dashed #dce3ec;border-radius:14px;text-align:center;color:#7f899b}
      @media(max-width:1050px){.shp-live,.shp-strip{grid-template-columns:1fr}.shp-tools{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){.shp-tools{grid-template-columns:repeat(2,minmax(0,1fr))}.shp-two,.shp-metrics{grid-template-columns:1fr}.shp-topic{grid-template-columns:1fr}.shp-live{grid-template-columns:1fr}}
    `; document.head.appendChild(s);
  }

  async function load(){
    const {data:{user}}=await db.auth.getUser(); if(!user)return false; P.user=user;
    const ago=new Date(Date.now()-1000*60*60*24*190).toISOString();
    const q=await Promise.all([
      db.from('study_presence').select('*').gte('last_seen_at',new Date(Date.now()-1000*60*60*6).toISOString()),
      db.from('study_focus_rounds').select('*').gte('created_at',ago), db.from('study_focus_members').select('*'),
      db.from('study_flashcards').select('*').order('created_at',{ascending:false}), db.from('study_flashcard_reviews').select('*').eq('user_id',user.id),
      db.from('study_notes').select('*').order('created_at',{ascending:false}), db.from('study_resources').select('*').order('created_at',{ascending:false}),
      db.from('study_targets').select('*').eq('user_id',user.id).order('target_date'), db.from('study_teach_sessions').select('*').gte('created_at',ago), db.from('study_teach_feedback').select('*'),
      db.from('study_rooms').select('*').order('created_at',{ascending:false}), db.from('study_room_members').select('*'),
      db.from('study_tasks').select('*'), db.from('study_task_completions').select('*'), db.from('study_schedules').select('*'),
      db.from('study_quizzes').select('*'), db.from('study_quiz_questions').select('*'), db.from('study_quiz_answers').select('*'),
      db.from('public_profiles').select('user_id,display_name,username,is_visible'), db.from('activity_types').select('*').eq('user_id',user.id), db.from('activity_sessions').select('*').eq('user_id',user.id).gte('started_at',ago)
    ]);
    if(q.some(x=>x.error)){console.warn('Study+ load failed',q.find(x=>x.error)?.error);return false}
    [P.presence,P.rounds,P.focusMembers,P.flashcards,P.reviews,P.notes,P.resources,P.targets,P.teach,P.teachFeedback,P.rooms,P.members,P.tasks,P.completions,P.schedules,P.quizzes,P.questions,P.answers,P.profiles,P.activityTypes,P.activitySessions]=q.map(x=>x.data||[]);
    P.loaded=true; return true;
  }

  function ownPresence(){return P.presence.find(x=>x.user_id===P.user?.id)}
  function recentPeople(){
    const own=ownPresence(), now=Date.now();
    const topic=norm(own?.topic);
    let a=P.presence.filter(x=>x.user_id!==P.user?.id && now-new Date(x.last_seen_at).getTime()<7200000);
    if(topic)a=a.filter(x=>norm(x.topic)===topic || norm(x.topic).includes(topic) || topic.includes(norm(x.topic)));
    return a.sort((x,y)=>new Date(y.last_seen_at)-new Date(x.last_seen_at)).slice(0,8);
  }
  function ownActiveFocus(){
    const m=P.focusMembers.find(x=>x.user_id===P.user?.id&&!x.ended_at);
    if(!m)return null; const r=P.rounds.find(x=>x.id===m.round_id); return r?{round:r,member:m}:null;
  }
  function roomAccessible(id){if(!id)return true;return P.rooms.some(r=>r.id===id&&(r.owner_id===P.user.id||P.members.some(m=>m.room_id===id&&m.user_id===P.user.id)))}
  function myRooms(){return P.rooms.filter(r=>r.owner_id===P.user.id||P.members.some(m=>m.room_id===r.id&&m.user_id===P.user.id))}

  function topicStats(){
    const map=new Map();
    P.answers.filter(a=>a.user_id===P.user?.id).forEach(a=>{
      const q=P.questions.find(x=>x.id===a.question_id); if(!q)return;
      const quiz=P.quizzes.find(x=>x.id===q.quiz_id); const topic=(q.topic||quiz?.title||'General').trim();
      const x=map.get(topic)||{topic,correct:0,total:0}; x.total++; if(a.is_correct)x.correct++; map.set(topic,x);
    });
    return [...map.values()].map(x=>({...x,accuracy:x.total?Math.round(x.correct/x.total*100):0})).sort((a,b)=>a.accuracy-b.accuracy);
  }
  function focusMinutes(days=7){
    const since=Date.now()-days*86400000; let total=0;
    P.focusMembers.filter(m=>m.user_id===P.user?.id&&m.ended_at).forEach(m=>{const r=P.rounds.find(x=>x.id===m.round_id);if(!r)return;const st=new Date(r.starts_at).getTime();if(st<since)return;total+=mins(new Date(r.starts_at),new Date(m.ended_at))});
    return total;
  }
  function streak(){
    const set=new Set(); P.focusMembers.filter(m=>m.user_id===P.user?.id&&m.ended_at).forEach(m=>{const r=P.rounds.find(x=>x.id===m.round_id);if(r)set.add(new Date(r.starts_at).toDateString())});
    let n=0,d=new Date(); for(let i=0;i<60;i++){if(set.has(d.toDateString()))n++;else if(i>0)break;d.setDate(d.getDate()-1)} return n;
  }
  function quizAccuracy(days=30){const since=Date.now()-days*86400000;const a=P.answers.filter(x=>x.user_id===P.user?.id&&new Date(x.answered_at).getTime()>=since);return a.length?Math.round(a.filter(x=>x.is_correct).length/a.length*100):0}
  function dueCards(){const now=Date.now();return P.flashcards.filter(c=>{const r=P.reviews.find(x=>x.card_id===c.id);return !r||new Date(r.next_review_at).getTime()<=now})}
  function incompleteTasks(){const mine=new Set(P.completions.filter(c=>c.user_id===P.user?.id).map(c=>c.task_id));return P.tasks.filter(t=>!mine.has(t.id)&&roomAccessible(t.room_id)).sort((a,b)=>new Date(a.due_at||'2999')-new Date(b.due_at||'2999'))}
  function coach(){
    const weak=topicStats()[0], due=dueCards().length, tasks=incompleteTasks().length, nextTarget=P.targets.find(t=>t.target_date&&new Date(t.target_date)>=new Date());
    if(weak&&weak.total>=3&&weak.accuracy<70)return {title:`Study ${weak.topic} next`,text:`Your quiz accuracy there is ${weak.accuracy}%. Review it before repeating stronger topics.`};
    if(due)return {title:`Review ${due} due flashcard${due===1?'':'s'}`,text:'Spaced repetition is due now; clearing this queue is likely higher value than starting a new topic.'};
    if(tasks)return {title:`Finish ${Math.min(3,tasks)} pending study task${tasks===1?'':'s'}`,text:'Your room checklist already contains unfinished work. Close those loops first.'};
    if(nextTarget)return {title:`Move ${nextTarget.title} forward`,text:`Your target is ${nextTarget.target_date}. Use a 50-minute focus block on its next unfinished unit.`};
    return {title:'Choose one topic and start a 50-minute focus block',text:'Medora will learn from your focus sessions, quiz results and flashcard reviews as data accumulates.'};
  }

  function panelHTML(){
    const own=ownPresence(), people=recentPeople(), active=ownActiveFocus(), c=coach(), mission=incompleteTasks().slice(0,3), weak=topicStats().slice(0,3);
    return `<section id="shpPanel">
      <div class="shp-live">
        <article class="shp-box"><h3>Studying now</h3><p>Set the topic you are studying. Medora keeps you visible for the current study window, not only the exact second.</p>
          <div class="shp-row"><input id="shpTopic" class="shp-input" placeholder="e.g. Microbiology" value="${esc(own?.topic||'')}"><select id="shpVisibility" class="shp-select"><option value="connections" ${own?.visibility==='connections'?'selected':''}>Connections</option><option value="public" ${own?.visibility==='public'?'selected':''}>Everyone</option><option value="room" ${own?.visibility==='room'?'selected':''}>Room only</option><option value="private" ${own?.visibility==='private'?'selected':''}>Private</option></select><button class="shp-btn primary" data-shp-presence>${own?.status==='studying'?'Update':'Start studying'}</button>${own?'<button class="shp-btn stop" data-shp-stop-presence>Stop</button>':''}</div>
          ${active?`<div class="shp-focus-live"><small>FOCUS SESSION</small><strong>${esc(active.round.topic)}</strong><strong class="shp-focus-time" data-shp-focus-clock>00:00</strong><small>${esc(roomName(active.round.room_id))}</small><div class="shp-row"><button class="shp-btn stop" data-shp-end-focus>End focus</button></div></div>`:''}
        </article>
        <article class="shp-box"><h3>${own?.topic?`Also studying ${esc(own.topic)}`:'People studying this period'}</h3><p>“Now” means active in the last 15 minutes; “this period” means seen within roughly 2 hours.</p><div class="shp-presence-list">${people.length?people.map(p=>{const live=p.status==='studying'&&Date.now()-new Date(p.last_seen_at).getTime()<900000;return `<div class="shp-person"><span class="shp-avatar">${esc(personName(p.user_id).slice(0,1).toUpperCase())}</span><div><strong>${esc(personName(p.user_id))}</strong><small>${esc(p.topic)}${p.subject?` · ${esc(p.subject)}`:''}</small></div><span class="shp-state ${live?'':'period'}">${live?'Now':'This period'}</span></div>`}).join(''):'<div class="shp-empty">No matching study partners visible yet.</div>'}</div></article>
      </div>
      <div class="shp-tools">
        <button class="shp-tool" data-shp-tool="focus"><span>⏱️</span><strong>Focus Room</strong><small>25 / 50 / 90 min, solo or together, with Study activity tracking.</small></button>
        <button class="shp-tool" data-shp-tool="flash"><span>🧠</span><strong>Flashcards</strong><small>Spaced repetition, room decks and fast review sessions.</small></button>
        <button class="shp-tool" data-shp-tool="insights"><span>🗺️</span><strong>Weakness Map</strong><small>Strong, developing and weak topics from quiz performance.</small></button>
        <button class="shp-tool" data-shp-tool="exam"><span>🎯</span><strong>Exam / Target</strong><small>Countdown, syllabus completion and transparent readiness score.</small></button>
        <button class="shp-tool" data-shp-tool="resources"><span>🗂️</span><strong>Notes & Resources</strong><small>Pinned notes, essential resources and room knowledge.</small></button>
        <button class="shp-tool" data-shp-tool="teach"><span>🧑‍🏫</span><strong>Teach the Room</strong><small>Explain a topic for 3–5 minutes and collect clarity feedback.</small></button>
        <button class="shp-tool" data-shp-tool="recap"><span>📊</span><strong>Study Recap</strong><small>Hours, tasks, quizzes, streaks, flashcards and next-step advice.</small></button>
        <button class="shp-tool" data-shp-tool="whatnow"><span>✨</span><strong>What should I study now?</strong><small>One recommendation from weak topics, due cards, tasks and targets.</small></button>
      </div>
      <div class="shp-strip"><article class="shp-mission"><h3>Today's mission 🚀</h3><p>Small visible wins from your room checklists.</p><div class="shp-mission-list">${mission.length?mission.map(t=>`<div class="shp-mission-item"><span>${esc(t.title)}</span><b>${esc(roomName(t.room_id))}</b></div>`).join(''):'<div class="shp-empty">No unfinished room tasks. Create a checklist in Study Rooms.</div>'}</div><div class="shp-chiprow"><span class="shp-chip">🔥 ${streak()} day streak</span><span class="shp-chip">⏱ ${dur(focusMinutes(7))} focused this week</span><span class="shp-chip">🧠 ${quizAccuracy(30)}% quiz accuracy</span></div></article>
        <article class="shp-coach"><h3>Medora Study Coach</h3><p><b>${esc(c.title)}</b></p><p>${esc(c.text)}</p>${weak.length?`<div class="shp-chiprow">${weak.map(x=>`<span class="shp-chip">${esc(x.topic)} ${x.accuracy}%</span>`).join('')}</div>`:''}</article></div>
      <div id="shpModal"></div>
    </section>`;
  }

  async function inject(){
    if(!studyOpen())return; const root=$('.sh-root'); if(!root)return;
    if(!P.loaded)await load();
    let panel=$('#shpPanel'); if(panel)panel.remove();
    const tabs=root.querySelector('.sh-tabs'); const wrap=document.createElement('div'); wrap.innerHTML=panelHTML(); const node=wrap.firstElementChild;
    if(tabs)tabs.insertAdjacentElement('afterend',node); else root.appendChild(node);
    bindPanel(); startClock();
  }

  function bindPanel(){
    $('[data-shp-presence]')?.addEventListener('click',setPresence);
    $('[data-shp-stop-presence]')?.addEventListener('click',stopPresence);
    $('[data-shp-end-focus]')?.addEventListener('click',endFocus);
    $$('[data-shp-tool]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.shpTool)));
  }

  async function setPresence(){
    const topic=$('#shpTopic')?.value.trim(); if(!topic)return alert('Enter what you are studying.');
    const visibility=$('#shpVisibility')?.value||'connections'; const now=new Date().toISOString(); const current=ownPresence();
    const payload={user_id:P.user.id,topic,status:'studying',visibility,last_seen_at:now,updated_at:now,started_at:current&&norm(current.topic)===norm(topic)?current.started_at:now};
    const {data,error}=await db.from('study_presence').upsert(payload,{onConflict:'user_id'}).select().single(); if(error)return alert(error.message);
    P.presence=P.presence.filter(x=>x.user_id!==P.user.id);P.presence.push(data); heartbeat(); inject();
  }
  async function stopPresence(){const p=ownPresence();if(!p)return;const {data}=await db.from('study_presence').update({status:'away',last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('user_id',P.user.id).select().single();if(data){P.presence=P.presence.filter(x=>x.user_id!==P.user.id);P.presence.push(data)}clearInterval(P.heartbeat);inject()}
  function heartbeat(){clearInterval(P.heartbeat);P.heartbeat=setInterval(async()=>{const p=ownPresence();if(!p||p.status!=='studying')return;const now=new Date().toISOString();await db.from('study_presence').update({last_seen_at:now,updated_at:now}).eq('user_id',P.user.id)},60000)}

  function modal(html){const h=$('#shpModal');if(h)h.innerHTML=`<div class="shp-modal-bg"><section class="shp-modal"><div class="shp-modal-h"><div>${html.title}</div><button class="shp-x" data-shp-close>×</button></div>${html.body}</section></div>`; $$('[data-shp-close]').forEach(b=>b.onclick=()=>{if(h)h.innerHTML=''})}
  function roomOptions(){return `<option value="">Personal / no room</option>${myRooms().map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}`}

  function openTool(type){({focus:focusModal,flash:flashModal,insights:insightsModal,exam:examModal,resources:resourcesModal,teach:teachModal,recap:recapModal,whatnow:whatNowModal}[type]||(()=>{}))()}

  function focusModal(){
    const open=P.rounds.filter(r=>['open','running'].includes(r.status)&&(!r.room_id||roomAccessible(r.room_id))).filter(r=>!P.focusMembers.some(m=>m.round_id===r.id&&m.user_id===P.user.id&&m.ended_at));
    modal({title:'<span class="sh-ey" style="color:#71809b">FOCUS ROOM</span><h2>Protect one block of attention.</h2>',body:`<form id="shpFocusForm" class="shp-form"><label>Topic<input id="shpFocusTopic" required value="${esc(ownPresence()?.topic||'')}"></label><div class="shp-two"><label>Duration<select id="shpFocusMinutes"><option>25</option><option selected>50</option><option>90</option><option>120</option></select></label><label>Room<select id="shpFocusRoom">${roomOptions()}</select></label></div><label>Confidence before (1–5)<select id="shpConfidence"><option value="1">1 — very low</option><option value="2">2</option><option value="3" selected>3</option><option value="4">4</option><option value="5">5 — very high</option></select></label><div class="shp-modal-actions"><button class="shp-save" type="submit">Start focus →</button></div></form>${open.length?`<div class="shp-list"><h3>Join a live room</h3>${open.map(r=>`<div class="shp-card"><h4>${esc(r.topic)}</h4><small>${esc(roomName(r.room_id))} · ${r.planned_minutes} min</small><div class="shp-card-actions"><button class="good" data-shp-join-focus="${r.id}">Join</button></div></div>`).join('')}</div>`:''}`});
    $('#shpFocusForm')?.addEventListener('submit',e=>{e.preventDefault();startFocus()}); $$('[data-shp-join-focus]').forEach(b=>b.onclick=()=>joinFocus(b.dataset.shpJoinFocus));
  }
  async function studyActivityType(){let t=P.activityTypes.find(x=>norm(x.name)==='study');if(t)return t;const {data}=await db.from('activity_types').insert({user_id:P.user.id,name:'Study',icon:'📚',analysis_group:'productive',sort_order:2}).select().single();if(data){P.activityTypes.push(data);return data}return null}
  async function startActivity(topic){const open=P.activitySessions.find(x=>!x.ended_at);if(open){if(!confirm('Another Activity session is running. End it and start Study?'))return null;await db.from('activity_sessions').update({ended_at:new Date().toISOString()}).eq('id',open.id);open.ended_at=new Date().toISOString()}const t=await studyActivityType();if(!t)return null;const {data}=await db.from('activity_sessions').insert({user_id:P.user.id,activity_type_id:t.id,started_at:new Date().toISOString(),note:`Study focus: ${topic}`}).select().single();if(data)P.activitySessions.unshift(data);return data}
  async function startFocus(){if(ownActiveFocus())return alert('You already have a focus session running.');const topic=$('#shpFocusTopic').value.trim(),minutes=Number($('#shpFocusMinutes').value),room=$('#shpFocusRoom').value||null,confidence=Number($('#shpConfidence').value);if(!topic)return;const act=await startActivity(topic);if(act===null)return;const {data:r,error}=await db.from('study_focus_rounds').insert({room_id:room,created_by:P.user.id,topic,planned_minutes:minutes,status:'running',starts_at:new Date().toISOString()}).select().single();if(error)return alert(error.message);const {data:m,error:me}=await db.from('study_focus_members').insert({round_id:r.id,user_id:P.user.id,activity_session_id:act?.id||null,confidence_before:confidence}).select().single();if(me)return alert(me.message);P.rounds.unshift(r);P.focusMembers.push(m);await db.from('study_presence').upsert({user_id:P.user.id,room_id:room,topic,status:'studying',visibility:room?'room':'connections',started_at:r.starts_at,last_seen_at:r.starts_at,updated_at:r.starts_at},{onConflict:'user_id'});P.loaded=false;$('#shpModal').innerHTML='';await load();inject();heartbeat()}
  async function joinFocus(id){const r=P.rounds.find(x=>x.id===id);if(!r)return;const act=await startActivity(r.topic);if(act===null)return;const {error}=await db.from('study_focus_members').insert({round_id:id,user_id:P.user.id,activity_session_id:act?.id||null,confidence_before:3});if(error)return alert(error.message);await db.from('study_presence').upsert({user_id:P.user.id,room_id:r.room_id,topic:r.topic,status:'studying',visibility:r.room_id?'room':'connections',started_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id'});P.loaded=false;$('#shpModal').innerHTML='';await load();inject();heartbeat()}
  async function endFocus(){const a=ownActiveFocus();if(!a)return;let after=Number(prompt('Confidence after studying (1–5)?','4'));if(!Number.isFinite(after)||after<1||after>5)after=null;const end=new Date().toISOString();await db.from('study_focus_members').update({ended_at:end,confidence_after:after}).eq('round_id',a.round.id).eq('user_id',P.user.id);if(a.member.activity_session_id)await db.from('activity_sessions').update({ended_at:end}).eq('id',a.member.activity_session_id);if(a.round.created_by===P.user.id)await db.from('study_focus_rounds').update({status:'finished'}).eq('id',a.round.id);await db.from('study_presence').update({status:'away',last_seen_at:end,updated_at:end}).eq('user_id',P.user.id);P.loaded=false;await load();inject()}
  function startClock(){clearInterval(P.clock);P.clock=setInterval(()=>{const el=$('[data-shp-focus-clock]'),a=ownActiveFocus();if(!el||!a)return;const s=Math.floor((Date.now()-new Date(a.round.starts_at).getTime())/1000);el.textContent=`${pad(Math.floor(s/60))}:${pad(s%60)}`},1000)}

  function flashModal(){const due=dueCards();modal({title:'<span class="sh-ey" style="color:#71809b">FLASHCARDS</span><h2>Remember what matters.</h2>',body:`<div class="shp-metrics"><div class="shp-metric"><small>Cards</small><strong>${P.flashcards.length}</strong></div><div class="shp-metric"><small>Due now</small><strong>${due.length}</strong></div><div class="shp-metric"><small>Reviewed</small><strong>${P.reviews.filter(r=>r.reviewed_at).length}</strong></div></div><form id="shpCardForm" class="shp-form"><div class="shp-two"><label>Topic<input id="shpCardTopic" required></label><label>Room<select id="shpCardRoom">${roomOptions()}</select></label></div><label>Front<input id="shpCardFront" required></label><label>Back<textarea id="shpCardBack" rows="3" required></textarea></label><div class="shp-modal-actions"><button class="shp-save" type="submit">Add flashcard</button></div></form><div class="shp-list"><h3>Due review</h3>${due.slice(0,12).map(c=>`<div class="shp-card" data-card="${c.id}"><div class="shp-face">${esc(c.front)}</div><div class="shp-answer hidden" data-card-answer>${esc(c.back)}</div><div class="shp-card-actions"><button data-reveal>Reveal</button><button class="bad" data-review="again">Again</button><button data-review="hard">Hard</button><button class="good" data-review="good">Good</button><button class="good" data-review="easy">Easy</button></div></div>`).join('')||'<div class="shp-empty">No cards are due.</div>'}</div><p style="color:#858ea0;font-size:9px">For a competitive flashcard round, use Quiz Race with room members; card-to-race conversion is the next live-sync layer.</p>`});$('#shpCardForm')?.addEventListener('submit',addCard);$$('[data-reveal]').forEach(b=>b.onclick=()=>b.closest('[data-card]').querySelector('[data-card-answer]').classList.toggle('hidden'));$$('[data-review]').forEach(b=>b.onclick=()=>reviewCard(b.closest('[data-card]').dataset.card,b.dataset.review))}
  async function addCard(e){e.preventDefault();const {data,error}=await db.from('study_flashcards').insert({created_by:P.user.id,room_id:$('#shpCardRoom').value||null,topic:$('#shpCardTopic').value.trim(),front:$('#shpCardFront').value.trim(),back:$('#shpCardBack').value.trim()}).select().single();if(error)return alert(error.message);P.flashcards.unshift(data);flashModal()}
  async function reviewCard(id,result){const steps={again:0,hard:1,good:3,easy:7},prev=P.reviews.find(r=>r.card_id===id),days=result==='again'?0:Math.max(steps[result],(prev?.interval_days||0)+(result==='easy'?7:result==='good'?3:1));const next=new Date();next.setDate(next.getDate()+days);const {data}=await db.from('study_flashcard_reviews').upsert({card_id:id,user_id:P.user.id,last_result:result,interval_days:days,next_review_at:next.toISOString(),reviewed_at:new Date().toISOString()},{onConflict:'card_id,user_id'}).select().single();if(data){P.reviews=P.reviews.filter(x=>x.card_id!==id);P.reviews.push(data);flashModal()}}

  function insightsModal(){const stats=topicStats();modal({title:'<span class="sh-ey" style="color:#71809b">WEAKNESS MAP</span><h2>Study what needs you most.</h2>',body:`<div class="shp-metrics"><div class="shp-metric"><small>Quiz accuracy</small><strong>${quizAccuracy(90)}%</strong></div><div class="shp-metric"><small>Focus / 7 days</small><strong>${dur(focusMinutes(7))}</strong></div><div class="shp-metric"><small>Study streak</small><strong>${streak()}d</strong></div></div><div class="shp-topic-list">${stats.length?stats.map(x=>`<div class="shp-topic"><b>${esc(x.topic)}</b><div class="shp-track"><span style="width:${x.accuracy}%"></span></div><span>${x.accuracy}% · ${x.correct}/${x.total}</span></div>`).join(''):'<div class="shp-empty">Complete some room quizzes and your topic map will appear here.</div>'}</div><div class="shp-list"><div class="shp-rec"><b>How Medora labels topics</b><span>Weak &lt;70%, Developing 70–84%, Strong ≥85%. These are study signals, not academic diagnoses.</span></div></div>`})}

  function examModal(){modal({title:'<span class="sh-ey" style="color:#71809b">TARGET & READINESS</span><h2>Know what the countdown means.</h2>',body:`<form id="shpTargetForm" class="shp-form"><label>Exam / target<input id="shpTargetTitle" required placeholder="e.g. Microbiology final"></label><div class="shp-two"><label>Date<input id="shpTargetDate" type="date"></label><label>Unit label<input id="shpTargetUnit" value="topics"></label></div><div class="shp-two"><label>Total units<input id="shpTargetTotal" type="number" min="1"></label><label>Completed units<input id="shpTargetDone" type="number" min="0" value="0"></label></div><div class="shp-modal-actions"><button class="shp-save" type="submit">Save target</button></div></form><div class="shp-list">${P.targets.map(t=>{const prog=t.total_units?Math.min(100,Math.round(Number(t.completed_units)/Number(t.total_units)*100)):0,acc=quizAccuracy(30),cons=Math.min(100,Math.round(focusMinutes(7)/420*100)),read=Math.round(prog*.5+acc*.3+cons*.2),days=t.target_date?Math.ceil((new Date(t.target_date)-new Date())/86400000):null;return `<div class="shp-card"><h4>${esc(t.title)}</h4><small>${days!=null?`${days} days · `:''}${prog}% syllabus · ${read}% readiness</small><div class="shp-card-actions"><button data-target-plus="${t.id}">+1 ${esc(t.unit_label)}</button></div><p style="font-size:9px;color:#858ea0">Readiness = 50% syllabus progress + 30% recent quiz accuracy + 20% weekly focus consistency.</p></div>`}).join('')||'<div class="shp-empty">No exam target yet.</div>'}</div>`});$('#shpTargetForm')?.addEventListener('submit',saveTarget);$$('[data-target-plus]').forEach(b=>b.onclick=()=>targetPlus(b.dataset.targetPlus))}
  async function saveTarget(e){e.preventDefault();const {data,error}=await db.from('study_targets').insert({user_id:P.user.id,title:$('#shpTargetTitle').value.trim(),target_date:$('#shpTargetDate').value||null,total_units:Number($('#shpTargetTotal').value)||null,completed_units:Number($('#shpTargetDone').value)||0,unit_label:$('#shpTargetUnit').value.trim()||'topics'}).select().single();if(error)return alert(error.message);P.targets.push(data);examModal()}
  async function targetPlus(id){const t=P.targets.find(x=>x.id===id);if(!t)return;const val=Number(t.completed_units||0)+1;const {data}=await db.from('study_targets').update({completed_units:val,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(data){Object.assign(t,data);examModal()}}

  function resourcesModal(){modal({title:'<span class="sh-ey" style="color:#71809b">NOTES & RESOURCES</span><h2>Keep the room knowledge useful.</h2>',body:`<div class="shp-two"><form id="shpNoteForm" class="shp-form"><h3>New note</h3><label>Topic<input id="shpNoteTopic"></label><label>Room<select id="shpNoteRoom">${roomOptions()}</select></label><label>Note<textarea id="shpNoteBody" rows="4" required></textarea></label><label><input id="shpNotePinned" type="checkbox"> Pin this note</label><button class="shp-save" type="submit">Save note</button></form><form id="shpResForm" class="shp-form"><h3>New resource</h3><label>Title<input id="shpResTitle" required></label><label>Room<select id="shpResRoom">${roomOptions()}</select></label><label>URL<input id="shpResUrl" type="url"></label><label>Importance<select id="shpResImp"><option value="essential">Essential</option><option value="recommended" selected>Recommended</option><option value="extra">Extra</option></select></label><button class="shp-save" type="submit">Add resource</button></form></div><div class="shp-list"><h3>Recent</h3>${[...P.notes.slice(0,5).map(n=>`<div class="shp-card"><h4>${n.is_pinned?'📌 ':''}${esc(n.topic||'Note')}</h4><small>${esc(roomName(n.room_id))}</small><p>${esc(n.body)}</p></div>`),...P.resources.slice(0,5).map(r=>`<div class="shp-card"><h4>${esc(r.title)}</h4><small>${esc(r.importance)} · ${esc(roomName(r.room_id))}</small></div>`)].join('')||'<div class="shp-empty">No notes or resources yet.</div>'}</div>`});$('#shpNoteForm')?.addEventListener('submit',saveNote);$('#shpResForm')?.addEventListener('submit',saveResource)}
  async function saveNote(e){e.preventDefault();const {data,error}=await db.from('study_notes').insert({created_by:P.user.id,room_id:$('#shpNoteRoom').value||null,topic:$('#shpNoteTopic').value.trim(),body:$('#shpNoteBody').value.trim(),is_pinned:$('#shpNotePinned').checked}).select().single();if(error)return alert(error.message);P.notes.unshift(data);resourcesModal()}
  async function saveResource(e){e.preventDefault();const {data,error}=await db.from('study_resources').insert({created_by:P.user.id,room_id:$('#shpResRoom').value||null,title:$('#shpResTitle').value.trim(),url:$('#shpResUrl').value.trim()||null,importance:$('#shpResImp').value}).select().single();if(error)return alert(error.message);P.resources.unshift(data);resourcesModal()}

  function teachModal(){const rooms=myRooms();modal({title:'<span class="sh-ey" style="color:#71809b">TEACH THE ROOM</span><h2>Explain it to learn it.</h2>',body:`<form id="shpTeachForm" class="shp-form"><label>Room<select id="shpTeachRoom" required><option value="">Choose room</option>${rooms.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select></label><div class="shp-two"><label>Topic<input id="shpTeachTopic" required></label><label>Minutes<select id="shpTeachMin"><option>3</option><option selected>5</option><option>10</option></select></label></div><div class="shp-modal-actions"><button class="shp-save" type="submit">Start teaching</button></div></form><div class="shp-list">${P.teach.slice(0,8).map(t=>{const f=P.teachFeedback.filter(x=>x.session_id===t.id),avg=f.length?(f.reduce((s,x)=>s+x.clarity,0)/f.length).toFixed(1):'—';return `<div class="shp-card"><h4>${esc(t.topic)}</h4><small>${esc(personName(t.presenter_id))} · ${esc(roomName(t.room_id))} · clarity ${avg}/3</small>${t.presenter_id!==P.user.id?`<div class="shp-card-actions"><button data-teach-rate="${t.id}" data-rate="1">Need clarity</button><button data-teach-rate="${t.id}" data-rate="2">Clear</button><button class="good" data-teach-rate="${t.id}" data-rate="3">Very clear</button></div>`:''}</div>`}).join('')||'<div class="shp-empty">No teaching turns yet.</div>'}</div>`});$('#shpTeachForm')?.addEventListener('submit',saveTeach);$$('[data-teach-rate]').forEach(b=>b.onclick=()=>rateTeach(b.dataset.teachRate,Number(b.dataset.rate)))}
  async function saveTeach(e){e.preventDefault();const {data,error}=await db.from('study_teach_sessions').insert({room_id:$('#shpTeachRoom').value,presenter_id:P.user.id,topic:$('#shpTeachTopic').value.trim(),duration_minutes:Number($('#shpTeachMin').value)}).select().single();if(error)return alert(error.message);P.teach.unshift(data);teachModal()}
  async function rateTeach(id,clarity){const {data,error}=await db.from('study_teach_feedback').upsert({session_id:id,user_id:P.user.id,clarity},{onConflict:'session_id,user_id'}).select().single();if(error)return alert(error.message);P.teachFeedback=P.teachFeedback.filter(x=>!(x.session_id===id&&x.user_id===P.user.id));P.teachFeedback.push(data);teachModal()}

  function recapModal(){const fm=focusMinutes(7),acc=quizAccuracy(7),task7=P.completions.filter(c=>c.user_id===P.user.id&&Date.now()-new Date(c.completed_at).getTime()<604800000).length,rev7=P.reviews.filter(r=>r.reviewed_at&&Date.now()-new Date(r.reviewed_at).getTime()<604800000).length,stats=topicStats(),weak=stats[0];modal({title:'<span class="sh-ey" style="color:#71809b">WEEKLY RECAP</span><h2>What changed in your studying?</h2>',body:`<div class="shp-metrics"><div class="shp-metric"><small>Focus</small><strong>${dur(fm)}</strong></div><div class="shp-metric"><small>Tasks finished</small><strong>${task7}</strong></div><div class="shp-metric"><small>Quiz accuracy</small><strong>${acc}%</strong></div><div class="shp-metric"><small>Flashcards reviewed</small><strong>${rev7}</strong></div><div class="shp-metric"><small>Streak</small><strong>${streak()}d</strong></div><div class="shp-metric"><small>Weakest topic</small><strong>${esc(weak?.topic||'—')}</strong></div></div><div class="shp-list"><div class="shp-rec"><b>${esc(coach().title)}</b><span>${esc(coach().text)}</span></div><div class="shp-rec"><b>Room contribution</b><span>Checklist completions, quiz participation and focus attendance are all visible inputs for future room reports and friendly leagues.</span></div><div class="shp-rec"><b>Activity connection</b><span>Focus sessions started here are recorded as Study in Activity, so your broader weekly life report can compare study time with sleep, social media, work and recovery.</span></div></div>`})}
  function whatNowModal(){const c=coach();modal({title:'<span class="sh-ey" style="color:#71809b">WHAT SHOULD I STUDY NOW?</span><h2>${esc(c.title)}</h2>',body:`<div class="shp-rec"><b>Why this?</b><span>${esc(c.text)}</span></div><div class="shp-card-actions" style="margin-top:14px"><button class="good" data-shp-start-recommended>Start a 50-minute focus block</button><button data-shp-open-flash>Open flashcards</button></div>`});$('[data-shp-start-recommended]')?.addEventListener('click',()=>{const h=$('#shpModal');if(h)h.innerHTML='';focusModal()});$('[data-shp-open-flash]')?.addEventListener('click',flashModal)}

  function attach(){
    style();
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=$('.shp-modal-bg');if(m){m.remove();e.preventDefault();e.stopPropagation()}}},true);
    document.addEventListener('click',e=>{if(e.target.closest('[data-study-link]'))setTimeout(async()=>{P.loaded=false;await load();inject()},180)},true);
    const obs=new MutationObserver(()=>{if(studyOpen()&&$('.sh-root')&&!$('#shpPanel'))setTimeout(inject,80)});obs.observe(document.body,{childList:true,subtree:true});
    setInterval(async()=>{if(!studyOpen())return;P.loaded=false;await load();inject()},60000);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach,{once:true});else attach();
})();