(() => {
  "use strict";
  const cfg=window.MEDORA_CONFIG||{};
  if(!window.supabase?.createClient||!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY)return;
  const db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const S={user:null,trip:null,config:null,cities:[],places:[],hubs:[],stops:[],segments:[],steps:[],photos:new Map()};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const city=id=>S.cities.find(x=>x.id===id),place=id=>S.places.find(x=>x.id===id),hub=id=>S.hubs.find(x=>x.id===id);
  const ICON={origin:"⌂",place:"◎",hub:"⌖",stay:"🛏",transport:"→",break:"☕",arrival:"✓",walk:"🚶",metro:"Ⓜ",tram:"🚋",bus:"🚌",taxi:"🚕",car:"🚗",train:"🚆",flight:"✈",airport_transfer:"⇄",other:"→"};
  const TZ=[[/Alexandria|Cairo|Sphinx/i,'Africa/Cairo'],[/Budapest/i,'Europe/Budapest'],[/Zagreb/i,'Europe/Zagreb'],[/Bratislava|Most SNP/i,'Europe/Bratislava'],[/Athens/i,'Europe/Athens']];
  const PHOTO={
    'bud-basilica':"St. Stephen's Basilica, Budapest",'bud-parliament':'Hungarian Parliament Building','bud-shoes':'Shoes on the Danube Bank','bud-chain':'Széchenyi Chain Bridge','bud-buda':'Buda Castle','bud-fisher':"Fisherman's Bastion",'bud-matthias':'Matthias Church','bud-heroes':"Heroes' Square (Budapest)",'bud-szechenyi':'Széchenyi thermal bath','bud-market':'Great Market Hall (Budapest)',
    'zag-ban':'Ban Jelačić Square','zag-dolac':'Dolac Market','zag-cathedral':'Zagreb Cathedral','zag-tkalca':'Tkalčićeva Street','zag-stone':'Stone Gate (Zagreb)','zag-mark':"St. Mark's Church, Zagreb",'zag-broken':'Museum of Broken Relationships','zag-lotrscak':'Lotrščak Tower','zag-funicular':'Zagreb Funicular','zag-zrinjevac':'Zrinjevac','zag-advent':'Zagreb',
    'bra-blue':'Blue Church (Bratislava)','bra-main':'Old Town, Bratislava','bra-primate':"Primate's Palace",'bra-michael':"Michael's Gate",'bra-martin':"St Martin's Cathedral, Bratislava",'bra-castle':'Bratislava Castle','bra-ufo':'Most SNP','bra-hviez':'Hviezdoslav Square',
    'ath-acropolis':'Acropolis of Athens','ath-museum':'Acropolis Museum','ath-plaka':'Plaka','ath-agora':'Ancient Agora of Athens','ath-monast':'Monastiraki','ath-syntagma':'Syntagma Square'
  };

  function toast(msg,type=""){const n=$('#journeyToast');if(!n)return;n.textContent=msg;n.className=`journey-toast show ${type}`.trim();clearTimeout(toast.t);toast.t=setTimeout(()=>n.className='journey-toast',2600)}
  const tzFor=(n='')=>TZ.find(([r])=>r.test(n))?.[1];
  function fmtDT(v,name=''){if(!v)return'Time not stored';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat(undefined,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:tzFor(name)}).format(d)}
  function fmtDate(v){if(!v)return'';const d=new Date(`${v}T12:00:00`);return new Intl.DateTimeFormat(undefined,{weekday:'short',day:'numeric',month:'short'}).format(d)}
  const time=v=>v?String(v).slice(0,5):'—';
  function duration(a,b){if(!a||!b)return null;const A=String(a).split(':').map(Number),B=String(b).split(':').map(Number);let n=B[0]*60+B[1]-(A[0]*60+A[1]);if(n<0)n+=1440;return n}
  const searchMap=(x)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x||'')}`;
  function dirMap(a,b,mode=''){if(!a||!b)return searchMap(b||a);const tm=mode==='walk'?'walking':['bus','metro','tram','train'].includes(mode)?'transit':'driving';return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(a)}&destination=${encodeURIComponent(b)}&travelmode=${tm}`}

  async function load(){
    const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('Sign in to Medora first.');S.user=user;
    const {data:trips,error}=await db.from('travel_trips').select('*').eq('user_id',user.id).order('start_date');if(error)throw error;if(!trips?.length)throw new Error('No trip found.');S.trip=trips[0];const id=S.trip.id;
    const r=await Promise.all([
      db.from('travel_journey_config').select('*').eq('trip_id',id).maybeSingle(),db.from('travel_cities').select('*').eq('trip_id',id).order('order_index'),db.from('travel_places').select('*').eq('trip_id',id).order('order_index'),db.from('travel_hubs').select('*').eq('trip_id',id).order('order_index'),db.from('travel_route_stops').select('*').eq('trip_id',id).order('route_date').order('sequence'),db.from('travel_transport_segments').select('*').eq('trip_id',id).order('order_index')
    ]);const bad=r.find(x=>x.error);if(bad)throw bad.error;
    S.config=r[0].data||{trip_id:id,user_id:user.id,origin_name:'Your starting point',origin_address:null,current_step_key:null};S.cities=r[1].data||[];S.places=r[2].data||[];S.hubs=r[3].data||[];S.stops=r[4].data||[];S.segments=r[5].data||[];S.steps=build();
  }

  const seg=k=>S.segments.find(x=>x.segment_key===k);
  function stop(c,d,q){const id=S.cities.find(x=>x.city_name===c)?.id;return S.stops.find(x=>x.city_id===id&&x.route_date===d&&x.sequence===q)}
  function range(c,d,a,b){const id=S.cities.find(x=>x.city_name===c)?.id;return S.stops.filter(x=>x.city_id===id&&x.route_date===d&&x.sequence>=a&&x.sequence<=b).sort((x,y)=>x.sequence-y.sequence)}

  function origin(){return{key:'origin-alexandria',type:'origin',title:S.config.origin_name||'Your starting point',subtitle:'Your EURO journey begins here.',address:S.config.origin_address||S.config.origin_name,photoQuery:S.config.origin_name||'Alexandria Egypt'}}
  function transport(s){if(!s)return null;return{key:`segment:${s.segment_key}`,type:'transport',title:`Go to ${s.to_name}`,fromName:s.from_name,fromAddress:s.from_address,toName:s.to_name,toAddress:s.to_address,subtitle:[s.provider,s.service_number].filter(Boolean).join(' · ')||'Travel segment',mode:s.mode,duration:s.duration_minutes,departAt:s.depart_at,arriveAt:s.arrive_at,transportDetail:s.transport_detail,notes:s.notes,confirmed:s.is_confirmed,photoQuery:s.provider||s.to_name}}
  function arrived(key,s,title){if(!s)return null;return{key,type:'arrival',title:title||`You arrived at ${s.to_name}`,subtitle:'Arrival point',address:s.to_address||s.to_name,photoQuery:s.to_name,notes:'You are here now. Continue when you are ready.'}}
  function stay(key,hubKey,title){const h=S.hubs.find(x=>x.hub_key===hubKey);if(!h)return null;const c=city(h.city_id);return{key,type:'stay',title:title||`You are now at ${h.name}`,subtitle:`${c?.city_name||''} · Your base`,address:h.address||h.name,photoQuery:c?.city_name||h.name,hub:h,notes:'Drop your luggage / check in. From here, Medora starts the recommended sightseeing order.'}}
  function route(s){if(!s)return null;const p=place(s.place_id),h=hub(s.hub_id),c=city(s.city_id);let t=s.stop_type;if(t==='hub'&&h&&['hostel','hotel'].includes(h.hub_type))t='stay';if(t==='hub'&&Number(s.travel_minutes||0)===0)t='arrival';const name=p?.name||h?.name||s.title,target=p?.address||h?.address||name;return{key:`route:${s.id}`,type:t,title:t==='hub'&&h?`Go to ${h.name}`:name,subtitle:`${c?.city_name||''} · ${fmtDate(s.route_date)}`,address:target,toName:name,toAddress:target,mode:s.travel_mode,duration:Number(s.travel_minutes||0),visitDuration:duration(s.planned_start,s.planned_end),start:s.planned_start,end:s.planned_end,transportDetail:s.transport_detail,notes:s.notes,hard:s.is_hard_deadline,place:p,hub:h,route:s,photoQuery:p?PHOTO[p.place_key]||s.photo_query||p.name:(h&&['hostel','hotel'].includes(h.hub_type)?c?.city_name:h?.name)||s.photo_query||s.title}}

  function build(){const a=[],P=x=>x&&a.push(x);const road=seg('egypt-road-to-spx'),flight=seg('spx-bud-flight');P(origin());P(transport(road));P(arrived('spx-arrived',road,'You are now at Sphinx International Airport'));P(transport(flight));P(arrived('bud-arrived',flight,'You have arrived in Budapest'));P(transport(seg('bud-airport-hostel')));P(stay('bud-hostel-arrived','bud-hostel','You are now at Maverick Athenaeum'));range('Budapest','2026-12-28',2,12).forEach(x=>P(route(x)));range('Budapest','2026-12-29',1,4).forEach(x=>P(route(x)));P(transport(seg('bud-zag-bus')));P(route(stop('Zagreb','2026-12-29',1)));P(transport(seg('zag-bus-hostel')));P(stay('zag-hostel-arrived','zag-hostel','You are now at Funk Lounge Hostel'));range('Zagreb','2026-12-29',3,6).forEach(x=>P(route(x)));range('Zagreb','2026-12-30',1,12).forEach(x=>P(route(x)));P(transport(seg('zag-bra-bus')));P(route(stop('Bratislava','2026-12-31',1)));P(transport(seg('bra-stop-hostel')));P(stay('bra-hostel-arrived','bra-hostel','You are now at Zen Zone Hostel'));range('Bratislava','2026-12-31',3,12).forEach(x=>P(route(x)));range('Bratislava','2027-01-01',1,5).forEach(x=>P(route(x)));P(transport(seg('bra-ath-flight')));P(route(stop('Athens','2027-01-01',1)));P(transport(seg('ath-airport-stay')));P(stay('ath-stay-arrived','ath-stay','You are now at your Athens stay'));range('Athens','2027-01-01',3,3).forEach(x=>P(route(x)));range('Athens','2027-01-02',1,11).forEach(x=>P(route(x)));P(transport(seg('ath-cai-flight')));P({key:'trip-finish',type:'arrival',title:'You are back in Cairo',subtitle:'Journey complete',address:'Cairo International Airport, Cairo, Egypt',photoQuery:'Cairo International Airport'});return a.map((x,i)=>({...x,index:i}))}

  function currentIndex(){const k=S.config.current_step_key||S.steps[0]?.key,i=S.steps.findIndex(x=>x.key===k);return i<0?0:i}
  function loc(step){return step?.toAddress||step?.address||step?.toName||step?.title||''}
  function prevLoc(i){for(let n=i-1;n>=0;n--){const x=loc(S.steps[n]);if(x)return x}return S.config.origin_address||S.config.origin_name||''}
  function mapFor(step,i){if(step.type==='transport'){return step.mode==='flight'?searchMap(step.fromAddress||step.fromName):dirMap(step.fromAddress||step.fromName,step.toAddress||step.toName,step.mode)}return dirMap(prevLoc(i),step.address||step.title,step.mode||'walk')}
  function state(i,cur){return i<cur?'done':i===cur?'current':'future'}
  function currentWhere(step){return step?.type==='transport'?(step.fromName||'Departure point'):(step?.title||'Journey')}
  function currentInstruction(step){if(!step)return'';if(step.type==='transport')return `Next: ${step.title}. ${step.transportDetail||step.subtitle||''}`;if(step.type==='stay')return `${step.notes||''}`;if(step.type==='place')return `You reached this stop. ${step.notes||''}`;return step.notes||step.subtitle||''}
  function chips(step){const a=[];if(step.duration)a.push(`${ICON[step.mode]||'→'} ${step.duration} min`);if(step.start)a.push(`⏱ ${time(step.start)}${step.end&&step.end!==step.start?`–${time(step.end)}`:''}`);if(step.visitDuration&&step.type==='place')a.push(`Visit ≈ ${step.visitDuration} min`);if(step.hard)a.push('HARD TIME');if(step.confirmed)a.push('CONFIRMED');return a}
  function transportBox(step){if(step.type!=='transport')return'';return `<div class="transport-card"><div class="transport-logo">${ICON[step.mode]||'→'}</div><div><strong>${esc([step.subtitle].filter(Boolean).join(''))}</strong><small>${esc(step.fromName)} → ${esc(step.toName)}</small><div class="transport-times"><span>Depart: ${esc(fmtDT(step.departAt,step.fromName))}</span><span>Arrive: ${esc(fmtDT(step.arriveAt,step.toName))}</span>${step.duration?`<span>${step.duration} min</span>`:''}</div></div></div>`}
  function placeInfo(step){const p=step.place;if(!p)return'';return `${p.why_visit||p.notes?`<div class="transport-detail"><strong>Why visit:</strong> ${esc(p.why_visit||p.notes)}</div>`:''}${p.opening_hours_text?`<div class="transport-detail"><strong>Opening:</strong> ${esc(p.opening_hours_text)}</div>`:''}${p.entry_fee_note?`<div class="transport-detail"><strong>Entry:</strong> ${esc(p.entry_fee_note)}</div>`:''}`}
  function stepCard(step,i,cur){const st=state(i,cur),cc=chips(step);return `<article class="journey-step ${st}"><div class="journey-node">${i+1}</div><div class="journey-step-card"><div class="step-grid"><div class="step-photo photo-skeleton" data-photo-query="${esc(step.photoQuery||step.title)}"></div><div class="step-copy"><div class="step-top"><div><span class="step-type">${esc(step.type)}</span><h3>${esc(step.title)}</h3></div>${st==='done'?'<span class="route-chip done">DONE</span>':st==='current'?'<span class="route-chip time">NOW</span>':''}</div><p>${esc(step.subtitle||step.notes||'')}</p><div class="step-route">${cc.map(x=>`<span class="route-chip ${x==='HARD TIME'?'hard':''}">${esc(x)}</span>`).join('')}</div>${step.transportDetail?`<div class="transport-detail"><strong>How to go:</strong> ${esc(step.transportDetail)}</div>`:''}${transportBox(step)}${placeInfo(step)}<div class="step-actions"><a class="jbtn small dark" href="${mapFor(step,i)}" target="_blank" rel="noopener">Map ↗</a>${st==='current'?`<button class="jbtn small primary" data-done="${esc(step.key)}" type="button">${step.type==='place'?'✓ Visited':'✓ Reached / done'}</button>`:''}${step.place?.source_url?`<a class="jbtn small" href="${esc(step.place.source_url)}" target="_blank" rel="noopener">Info ↗</a>`:''}</div></div></div></div></article>`}

  function render(){const root=$('#journeyRoot'),cur=currentIndex(),now=S.steps[cur],next=S.steps[cur+1],pct=Math.round(cur/Math.max(1,S.steps.length-1)*100);root.innerHTML=`<header class="journey-top"><div class="journey-brand"><img src="assets/medora-mark.svg" alt=""><div><strong>Medora Travel</strong><small>Virtual Journey</small></div></div><span class="journey-private">🔒 Private to your account</span></header><section class="journey-hero"><span class="journey-eyebrow">VIRTUAL PATHWAY · ${esc(S.trip.title||'YOUR TRIP')}</span><h1>Where am I? What next?</h1><p>No dashboards. No travel clutter. Just your current place, the next move, the exact timing we know, the recommended route and a map button at every step.</p><div class="journey-hero-meta"><span class="journey-pill">Step ${cur+1} / ${S.steps.length}</span><span class="journey-pill">${pct}% complete</span></div><div class="journey-progress"><span style="width:${pct}%"></span></div></section><section class="current-wrap"><article class="current-card"><div class="current-photo photo-skeleton" data-photo-query="${esc(now?.photoQuery||currentWhere(now))}"><div class="current-photo-copy"><span>YOU ARE NOW HERE</span><h2>${esc(currentWhere(now))}</h2><p>${esc(currentInstruction(now))}</p></div></div><div class="current-body"><div class="current-actions"><a class="jbtn dark" href="${mapFor(now,cur)}" target="_blank" rel="noopener">Open Map ↗</a><button class="jbtn primary" type="button" data-done="${esc(now.key)}">${now.type==='place'?'✓ I visited this place':'✓ Reached / done'}</button></div></div></article><aside class="next-card"><span class="label">YOUR NEXT MOVE</span><h3>${esc(next?.title||'Journey complete')}</h3>${next?`<div class="next-route"><div class="next-icon">${ICON[next.mode]||ICON[next.type]||'→'}</div><div><strong>${next.duration?`${next.duration} min · `:''}${esc((next.mode||next.type||'next').replaceAll('_',' '))}</strong><small>${esc(next.transportDetail||next.notes||next.subtitle||'Follow the next step.')}</small></div></div>${transportBox(next)}<div class="card-actions"><a class="jbtn dark" href="${mapFor(next,cur+1)}" target="_blank" rel="noopener">Map next ↗</a></div>`:'<div class="journey-warning">Your trip pathway is complete.</div>'}<div class="journey-warning">Map gives the live route. Recheck real-time traffic, platform/gate and holiday opening information at the time of travel.</div></aside></section><section class="journey-section"><div class="journey-section-head"><div><h2>The full journey</h2><p>The app advances card by card as you reach each airport, hostel, attraction and transport connection.</p></div></div><div class="journey-timeline">${S.steps.map((x,i)=>stepCard(x,i,cur)).join('')}</div></section>`;bind();photos()}

  async function advance(key){const i=S.steps.findIndex(x=>x.key===key);if(i<0)return;const st=S.steps[i],next=S.steps[Math.min(i+1,S.steps.length-1)],now=new Date().toISOString();if(st.place){await db.from('travel_places').update({visit_status:'visited',is_visited:true,found_at:st.place.found_at||now,visited_at:now,updated_at:now}).eq('id',st.place.id)}if(st.route)await db.from('travel_route_stops').update({status:st.place?'visited':'done',updated_at:now}).eq('id',st.route.id);const {data,error}=await db.from('travel_journey_config').upsert({trip_id:S.trip.id,user_id:S.user.id,current_step_key:next.key,started_at:S.config.started_at||now,updated_at:now},{onConflict:'trip_id'}).select().single();if(error)return toast(error.message,'error');S.config={...S.config,...data};toast('Next step ready.','success');render();setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),80)}
  function bind(){$$('[data-done]').forEach(b=>b.onclick=()=>advance(b.dataset.done))}

  async function wiki(q){q=String(q||'').trim();if(!q)return null;if(S.photos.has(q))return S.photos.get(q);const cache=localStorage.getItem(`medoraPhoto:${q}`);if(cache){S.photos.set(q,cache);return cache}try{const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(q.replaceAll(' ','_'))}`);if(!r.ok)return null;const j=await r.json(),u=j.originalimage?.source||j.thumbnail?.source||null;if(u){S.photos.set(q,u);try{localStorage.setItem(`medoraPhoto:${q}`,u)}catch{}}return u}catch{return null}}
  async function photos(){for(const n of $$('[data-photo-query]')){if(n.dataset.donePhoto)continue;n.dataset.donePhoto='1';const u=await wiki(n.dataset.photoQuery);n.style.backgroundImage=u?`url("${u.replaceAll('"','%22')}")`:'linear-gradient(135deg,#dce6ef,#c9d5e6)';n.classList.remove('photo-skeleton')}}

  async function boot(){try{await load();$('#journeyLoading')?.classList.add('hidden');$('#journeyRoot')?.classList.remove('hidden');render()}catch(e){console.error(e);$('#journeyLoading').innerHTML=`<div><strong>Travel journey could not load.</strong><small style="display:block;margin-top:6px">${esc(e.message||'Unknown error')}</small></div>`}}
  boot();
})();